package co.com.ebsa.ebsa_nexus.application.service.novelty;

import co.com.ebsa.ebsa_nexus.application.dto.request.novelty.StatisticalReportRequest;
import co.com.ebsa.ebsa_nexus.domain.entity.Novelty;
import co.com.ebsa.ebsa_nexus.domain.entity.StatisticalReport;
import co.com.ebsa.ebsa_nexus.domain.enums.NoveltyReason;
import co.com.ebsa.ebsa_nexus.domain.enums.NoveltyStatus;
import co.com.ebsa.ebsa_nexus.domain.exception.novelty.NoveltyOperationException;
import co.com.ebsa.ebsa_nexus.domain.repository.NoveltyRepository;
import co.com.ebsa.ebsa_nexus.domain.repository.StatisticalReportRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Service to generate reports and statistics for novelties
 * 
 * TODO: This service needs to be updated to use new Novelty fields:
 * - Use createdAt instead of reportedAt
 * - Use completedAt instead of resolvedAt  
 * - Update status values to CREADA, EN_CURSO, COMPLETADA, CERRADA, CANCELADA
 * - Remove references to verifiedByUserId
 * 
 * TEMPORARILY DISABLED until update is complete.
 */
@Service
@Transactional
public class NoveltyReportService {

    private final NoveltyRepository noveltyRepository;
    private final StatisticalReportRepository statisticalReportRepository;

    public NoveltyReportService(
            NoveltyRepository noveltyRepository,
            StatisticalReportRepository statisticalReportRepository) {
        this.noveltyRepository = noveltyRepository;
        this.statisticalReportRepository = statisticalReportRepository;
    }

    /**
     * Generate a comprehensive report for given period and filters
     * TEMPORARILY DISABLED - needs update for new schema
     */
    public StatisticalReport generateReport(StatisticalReportRequest request, Long generatedByUserId) {
        throw new NoveltyOperationException("Report generation temporarily disabled during schema migration");
    }

    /**
     * Get statistics summary for dashboard
     * TEMPORARILY DISABLED - needs update for new schema
     */
    @Transactional(readOnly = true)
    public Map<String, Object> getDashboardStatistics() {
        throw new NoveltyOperationException("Dashboard statistics temporarily disabled during schema migration");
    }

    /**
     * Get crew performance metrics
     * TEMPORARILY DISABLED - needs update for new schema
     */
    @Transactional(readOnly = true)
    public Map<String, Object> getCrewPerformance(Long crewId, LocalDate startDate, LocalDate endDate) {
        throw new NoveltyOperationException("Crew performance metrics temporarily disabled during schema migration");
    }

    /**
     * Get report by ID
     */
    @Transactional(readOnly = true)
    public StatisticalReport getReportById(Long reportId) {
        return statisticalReportRepository.findById(reportId)
                .orElseThrow(() -> new NoveltyOperationException("Report not found with id: " + reportId));
    }

    /**
     * Get all reports generated by user
     */
    @Transactional(readOnly = true)
    public List<StatisticalReport> getReportsByUser(Long userId) {
        return statisticalReportRepository.findByGeneratedByUserIdOrderByGeneratedAtDesc(userId);
    }
}
